######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 31 19:58:19 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += core gui svg xml

# Input
SOURCES += main.cpp
